//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUONG_TRINH_DAO_TAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUONG_TRINH_DAO_TAO()
        {
            this.CHUONG_TRINH_DAO_TAO_CHI_TIET = new HashSet<CHUONG_TRINH_DAO_TAO_CHI_TIET>();
        }
    
        public long DT_ID { get; set; }
        public string DT_MA { get; set; }
        public string DT_TEN { get; set; }
        public Nullable<long> DT_NIEN_KHOA_BAT_DAU { get; set; }
        public Nullable<long> DT_NIEN_KHOA_KET_THUC { get; set; }
        public string DT_GHI_CHU { get; set; }
        public Nullable<long> NGANH_ID { get; set; }
        public Nullable<long> HDT_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUONG_TRINH_DAO_TAO_CHI_TIET> CHUONG_TRINH_DAO_TAO_CHI_TIET { get; set; }
        public virtual NIEN_KHOA NIEN_KHOA { get; set; }
        public virtual NIEN_KHOA NIEN_KHOA1 { get; set; }
        public virtual DM_HE_DAO_TAO DM_HE_DAO_TAO { get; set; }
        public virtual DM_NGANH DM_NGANH { get; set; }
    }
}
