//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUONG_TRINH_DAO_TAO_CHI_TIET
    {
        public long DTCT_ID { get; set; }
        public Nullable<bool> DTCT_BAT_BUOC { get; set; }
        public Nullable<long> DT_ID { get; set; }
        public Nullable<long> HK_ID { get; set; }
        public Nullable<long> MH_ID { get; set; }
    
        public virtual CHUONG_TRINH_DAO_TAO CHUONG_TRINH_DAO_TAO { get; set; }
        public virtual HOC_KY HOC_KY { get; set; }
        public virtual DM_MON_HOC DM_MON_HOC { get; set; }
    }
}
