//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CHUC_DANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_CHUC_DANH()
        {
            this.DM_GIO_CHUAN_CHUC_DANH = new HashSet<DM_GIO_CHUAN_CHUC_DANH>();
            this.GV_CHUC_DANH = new HashSet<GV_CHUC_DANH>();
        }
    
        public long CD_ID { get; set; }
        public string CD_MA { get; set; }
        public string CD_TEN { get; set; }
        public string CD_GHI_CHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_GIO_CHUAN_CHUC_DANH> DM_GIO_CHUAN_CHUC_DANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GV_CHUC_DANH> GV_CHUC_DANH { get; set; }
    }
}
