//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CHUC_VU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_CHUC_VU()
        {
            this.DM_GIO_CHUAN_CHUC_VU = new HashSet<DM_GIO_CHUAN_CHUC_VU>();
            this.GV_CHUC_VU = new HashSet<GV_CHUC_VU>();
        }
    
        public long CV_ID { get; set; }
        public string CV_MA { get; set; }
        public string CV_TEN { get; set; }
        public string CV_GHI_CHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DM_GIO_CHUAN_CHUC_VU> DM_GIO_CHUAN_CHUC_VU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GV_CHUC_VU> GV_CHUC_VU { get; set; }
    }
}
