//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_GIO_CHUAN_CHUC_DANH
    {
        public long GCCD_ID { get; set; }
        public Nullable<long> CD_ID { get; set; }
        public Nullable<decimal> GCCD_SO_GIO { get; set; }
        public Nullable<System.DateTime> GCCD_NGAY_AP_DUNG { get; set; }
    
        public virtual DM_CHUC_DANH DM_CHUC_DANH { get; set; }
    }
}
