//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_GIO_CHUAN_CHUC_VU
    {
        public long GCCV_ID { get; set; }
        public Nullable<long> CV_ID { get; set; }
        public Nullable<decimal> GCCV_PHAN_TRAM { get; set; }
        public Nullable<System.DateTime> GCCV_NGAY_AP_DUNG { get; set; }
    
        public virtual DM_CHUC_VU DM_CHUC_VU { get; set; }
    }
}
