//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIANG_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIANG_VIEN()
        {
            this.GV_CHUC_DANH = new HashSet<GV_CHUC_DANH>();
            this.GV_CHUC_VU = new HashSet<GV_CHUC_VU>();
            this.GV_DON_VI = new HashSet<GV_DON_VI>();
            this.GV_GIANG_DAY = new HashSet<GV_GIANG_DAY>();
            this.LOP_CHUYEN_NGANH = new HashSet<LOP_CHUYEN_NGANH>();
        }
    
        public long GV_ID { get; set; }
        public string GV_MA { get; set; }
        public string GV_HOTEN { get; set; }
        public Nullable<bool> GV_GIOITINH { get; set; }
        public Nullable<System.DateTime> GV_NGAYSINH { get; set; }
        public Nullable<System.DateTime> GV_NGAY_BAT_DAU { get; set; }
        public Nullable<System.DateTime> GV_NGAY_KET_THUC { get; set; }
        public string GV_DIACHI { get; set; }
        public string GV_EMAIL { get; set; }
        public string GV_SDT { get; set; }
        public Nullable<long> DV_ID { get; set; }
    
        public virtual DM_DON_VI DM_DON_VI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GV_CHUC_DANH> GV_CHUC_DANH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GV_CHUC_VU> GV_CHUC_VU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GV_DON_VI> GV_DON_VI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GV_GIANG_DAY> GV_GIANG_DAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP_CHUYEN_NGANH> LOP_CHUYEN_NGANH { get; set; }
    }
}
