//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GV_DON_VI
    {
        public long GVDV_ID { get; set; }
        public Nullable<long> GV_ID { get; set; }
        public Nullable<long> DV_ID { get; set; }
        public Nullable<System.DateTime> GVDV_NGAY_BAT_DAU { get; set; }
        public Nullable<System.DateTime> GVDV_NGAY_KET_THUC { get; set; }
        public string GVDV_GHI_CHU { get; set; }
    
        public virtual DM_DON_VI DM_DON_VI { get; set; }
        public virtual GIANG_VIEN GIANG_VIEN { get; set; }
    }
}
