//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GV_GIANG_DAY
    {
        public long GVGD_ID { get; set; }
        public string GVGD_GHI_CHU { get; set; }
        public Nullable<long> PCGDCT_ID { get; set; }
        public Nullable<long> GV_ID { get; set; }
    
        public virtual GIANG_VIEN GIANG_VIEN { get; set; }
        public virtual PHAN_CONG_GIANG_DAY_CHI_TIET PHAN_CONG_GIANG_DAY_CHI_TIET { get; set; }
    }
}
