//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOA_HOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHOA_HOC()
        {
            this.KHOA_HOC_NIEN_KHOA = new HashSet<KHOA_HOC_NIEN_KHOA>();
            this.LOP_CHUYEN_NGANH = new HashSet<LOP_CHUYEN_NGANH>();
        }
    
        public long KH_ID { get; set; }
        public string KH_TEN { get; set; }
        public string KH_GHI_CHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOA_HOC_NIEN_KHOA> KHOA_HOC_NIEN_KHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP_CHUYEN_NGANH> LOP_CHUYEN_NGANH { get; set; }
    }
}
