//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOA_HOC_NIEN_KHOA
    {
        public long KHNK_ID { get; set; }
        public Nullable<long> KH_ID { get; set; }
        public Nullable<long> NK_ID { get; set; }
    
        public virtual KHOA_HOC KHOA_HOC { get; set; }
        public virtual NIEN_KHOA NIEN_KHOA { get; set; }
    }
}
