//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP_HOC_PHAN_CHI_TIET
    {
        public long LHPCT_ID { get; set; }
        public Nullable<int> LHPCT_SI_SO { get; set; }
        public Nullable<long> LHP_ID { get; set; }
    
        public virtual LOP_HOC_PHAN LOP_HOC_PHAN { get; set; }
    }
}
