//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP_CHUYEN_NGANH
    {
        public long LOP_ID { get; set; }
        public string LOP_MA { get; set; }
        public string LOP_TEN { get; set; }
        public Nullable<int> LOP_SI_SO { get; set; }
        public string LOP_GHI_CHU { get; set; }
        public Nullable<long> KH_ID { get; set; }
        public Nullable<long> NGANH_ID { get; set; }
        public Nullable<long> GV_ID { get; set; }
    
        public virtual DM_NGANH DM_NGANH { get; set; }
        public virtual GIANG_VIEN GIANG_VIEN { get; set; }
        public virtual KHOA_HOC KHOA_HOC { get; set; }
    }
}
