//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP_HOC_PHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP_HOC_PHAN()
        {
            this.LOP_HOC_PHAN_CHI_TIET = new HashSet<LOP_HOC_PHAN_CHI_TIET>();
            this.PHAN_CONG_GIANG_DAY_CHI_TIET = new HashSet<PHAN_CONG_GIANG_DAY_CHI_TIET>();
        }
    
        public long LHP_ID { get; set; }
        public string LHP_MA { get; set; }
        public string LHP_GHI_CHU { get; set; }
        public Nullable<long> MH_ID { get; set; }
    
        public virtual DM_MON_HOC DM_MON_HOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP_HOC_PHAN_CHI_TIET> LOP_HOC_PHAN_CHI_TIET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHAN_CONG_GIANG_DAY_CHI_TIET> PHAN_CONG_GIANG_DAY_CHI_TIET { get; set; }
    }
}
