//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MH_TIEN_QUYET
    {
        public long TQ_ID { get; set; }
        public Nullable<long> MH_ID { get; set; }
        public Nullable<long> MHTQ_ID { get; set; }
    
        public virtual DM_MON_HOC DM_MON_HOC { get; set; }
        public virtual DM_MON_HOC DM_MON_HOC1 { get; set; }
    }
}
