//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHAN_CONG_GIANG_DAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHAN_CONG_GIANG_DAY()
        {
            this.PHAN_CONG_GIANG_DAY_CHI_TIET = new HashSet<PHAN_CONG_GIANG_DAY_CHI_TIET>();
        }
    
        public long PCGD_ID { get; set; }
        public Nullable<long> NK_ID { get; set; }
    
        public virtual NIEN_KHOA NIEN_KHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHAN_CONG_GIANG_DAY_CHI_TIET> PHAN_CONG_GIANG_DAY_CHI_TIET { get; set; }
    }
}
