//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaoTao.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDTContext : DbContext
    {
        public QLDTContext()
            : base("name=QLDTContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUONG_TRINH_DAO_TAO> CHUONG_TRINH_DAO_TAO { get; set; }
        public virtual DbSet<CHUONG_TRINH_DAO_TAO_CHI_TIET> CHUONG_TRINH_DAO_TAO_CHI_TIET { get; set; }
        public virtual DbSet<DM_CHUC_DANH> DM_CHUC_DANH { get; set; }
        public virtual DbSet<DM_CHUC_VU> DM_CHUC_VU { get; set; }
        public virtual DbSet<DM_DON_VI> DM_DON_VI { get; set; }
        public virtual DbSet<DM_GIO_CHUAN_CHUC_DANH> DM_GIO_CHUAN_CHUC_DANH { get; set; }
        public virtual DbSet<DM_GIO_CHUAN_CHUC_VU> DM_GIO_CHUAN_CHUC_VU { get; set; }
        public virtual DbSet<DM_HE_DAO_TAO> DM_HE_DAO_TAO { get; set; }
        public virtual DbSet<DM_MON_HOC> DM_MON_HOC { get; set; }
        public virtual DbSet<DM_NGANH> DM_NGANH { get; set; }
        public virtual DbSet<GIANG_VIEN> GIANG_VIEN { get; set; }
        public virtual DbSet<GV_CHUC_DANH> GV_CHUC_DANH { get; set; }
        public virtual DbSet<GV_CHUC_VU> GV_CHUC_VU { get; set; }
        public virtual DbSet<GV_DON_VI> GV_DON_VI { get; set; }
        public virtual DbSet<GV_GIANG_DAY> GV_GIANG_DAY { get; set; }
        public virtual DbSet<HOC_KY> HOC_KY { get; set; }
        public virtual DbSet<KHOA_HOC> KHOA_HOC { get; set; }
        public virtual DbSet<KHOA_HOC_NIEN_KHOA> KHOA_HOC_NIEN_KHOA { get; set; }
        public virtual DbSet<LOP_CHUYEN_NGANH> LOP_CHUYEN_NGANH { get; set; }
        public virtual DbSet<LOP_HOC_PHAN> LOP_HOC_PHAN { get; set; }
        public virtual DbSet<LOP_HOC_PHAN_CHI_TIET> LOP_HOC_PHAN_CHI_TIET { get; set; }
        public virtual DbSet<MH_TIEN_QUYET> MH_TIEN_QUYET { get; set; }
        public virtual DbSet<NIEN_KHOA> NIEN_KHOA { get; set; }
        public virtual DbSet<PHAN_CONG_GIANG_DAY> PHAN_CONG_GIANG_DAY { get; set; }
        public virtual DbSet<PHAN_CONG_GIANG_DAY_CHI_TIET> PHAN_CONG_GIANG_DAY_CHI_TIET { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
